### ISSUE TITLE
Composer install error

### ISSUE THREAD

**Issue by ugintl** [carlomorgenstern/Alumni#1]
When I run composer install, it starts, but after downloading 3 vendor libraries, it gives an access denied error. chmod () access denied.

I am developing locally on acquia dev desktop. I have installed many sites using composer, but never had this issue.

**Comment by ugintl** [comment]
Sorry I was not using cmd as administrator. It worked

**Comment by MethodJules** [comment]
Hi,

 

all right. Can I ask you for what purpose do you want to use our Repo? I am just interested any maybe I can help you.

 

Best regards

 

Von: ugintl [mailto:notifications@github.com] 
Gesendet: Mittwoch, 11. Dezember 2019 13:03
An: MethodJules/Alumni <Alumni@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [MethodJules/Alumni] Composer install error (#1)

 

Sorry I was not using cmd as administrator. It worked

**Comment by ugintl** [comment]
I was searching for distributions for the purpose of building social network. Testing. The best so far is open social, but it is for D8
